### ISSUE TITLE
Roadmap: TODO

### ISSUE THREAD

**Issue by layaxx** [layaxx/s6_advaR#1]
TODO:

- [x] Hyperparameter darstellen (GB, RF)
- [x] Standardparameter der einzelnen packages darstellen
- [x] Übersicht über die Benchmarking Ergebnisse der packages
- [x] Welche Daten(sätze) sind denn jetzt besser für GB/RF ??
- [x] Add sources/references
